### ISSUE TITLE
Installing all dependencies result in Pytorch not seeing GPU

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/satflow#18]
When using conda to install rasterio, cfgrib, cartopy, satpy and Pytorch, there are inconsistencies in requirements and, if Pytorch is then installed, `torch.cuda.is_available()` returns `False`. The workaround right now is that I have two conda environments, one to preprocess the raw satellite and DEM data to Geotiff and numpy arrays, then switch to a different conda environment, the one in `environment.yml`, for actual training/experimenting/etc.

**Comment by JackKelly** [comment]
Sometimes conda tries to install `pytorch` from `conda-forge` which seems to result in installing the `cpu-only` version.

To force conda to install pytorch from the pytorch channel, you could try `conda install pytorch::pytorch` (unless you've already tried that, of course?!)

**Comment by jacobbieker** [comment]
That fixed it, thanks!
